#!/usr/bin/env python3
"""ProofGrid v3.1 real ÖKOBAUDAT environmental-source admission.

Binds an exact canonical ILCD package-content manifest, target process XML,
official extended service view, published terms page, and exact official
ÖKOBAUDAT profile-validation result. Admission is for normalization only.
"""
from __future__ import annotations
import argparse, hashlib, json, sys, xml.etree.ElementTree as ET
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any

ENGINE_NAME="RegenExcalibur ProofGrid Real ÖKOBAUDAT Environmental Source Admission"
ENGINE_VERSION="3.1.0"
VERDICT="REAL_ENVIRONMENTAL_SOURCE_ADMISSION_VERIFIABLE"
ZERO="0"*64
CANON="UTF-8 JSON; sorted keys; compact separators; ensure_ascii=false"
EXPECTED={
"uuid":"8347f9a7-f4ec-4a36-a266-a0281f5fd16d","version":"00.02.000","name":"Concrete C25/30","location":"DE","reference_year":"2023","valid_until":"2028","registration_number":"EPD-IZB-20230421-IBA1-DE","owner":"InformationsZentrum Beton GmbH","registration_authority":"Institut Bauen und Umwelt e. V.","format_version":"1.2","package_content_manifest_sha256":"c858c2712243684b094d843bd688b5ee062b0d8005f2cd2cef93bd7e4902e3a3","package_member_count":33,"process_path":"ILCD/processes/8347f9a7-f4ec-4a36-a266-a0281f5fd16d_00.02.000.xml","process_sha256":"18951c19002314adb6213d05783f8075553102a1bc57e22950d941a4804e445d","process_size":60812,"terms_sha256":"88d6a4ad8c63d16c1e24a4cee38a9f696d825248ceef87de572403b80bf9ed2d","terms_size":10371,"extended_sha256":"19571f40b2516345efb09d5ca423cb2b7f6c06debc4a69ee2d6837da52183c16","extended_size":77663,"gwp_indicator_uuid":"6a37f984-a4b3-458a-a20a-64418c145fa2","gwp_module":"A1-A3","gwp_value_decimal":"181"}
NS={"p":"http://lca.jrc.it/ILCD/Process","common":"http://lca.jrc.it/ILCD/Common","epd":"http://www.iai.kit.edu/EPD/2013","epd2":"http://www.indata.network/EPD/2019","xml":"http://www.w3.org/XML/1998/namespace"}
class AdmissionError(ValueError): pass
def require(c,m):
    if not c: raise AdmissionError(m)
def cbytes(v:Any)->bytes: return json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()
def pbytes(v:Any)->bytes: return (json.dumps(v,indent=2,sort_keys=True,ensure_ascii=False)+"\n").encode()
def sha(b:bytes)->str: return hashlib.sha256(b).hexdigest()
def load_json(path:Path):
    raw=Path(path).read_bytes(); obj=json.loads(raw.decode()); require(isinstance(obj,dict),f"expected JSON object: {path}"); return obj,raw
def canonical_decimal(text,label):
    require(isinstance(text,str) and text!="",f"{label} must be a Decimal string")
    try: d=Decimal(text)
    except InvalidOperation as exc: raise AdmissionError(f"{label} is not Decimal-compatible") from exc
    require(d.is_finite(),f"{label} must be finite"); rendered="0" if d==0 else format(d,"f")
    if "." in rendered: rendered=rendered.rstrip("0").rstrip(".")
    require(rendered==text,f"{label} is not canonical Decimal"); return text
def text_of(node): return None if node is None or node.text is None else node.text.strip()
def english_basename(root):
    for node in root.findall("./p:processInformation/p:dataSetInformation/p:name/p:baseName",NS):
        if node.attrib.get(f"{{{NS['xml']}}}lang")=="en": return (node.text or "").strip()
    raise AdmissionError("English baseName missing")
def parse_process(process_bytes:bytes)->dict[str,Any]:
    require(sha(process_bytes)==EXPECTED["process_sha256"],"target process SHA-256 mismatch"); require(len(process_bytes)==EXPECTED["process_size"],"target process byte size mismatch")
    try: root=ET.fromstring(process_bytes)
    except ET.ParseError as exc: raise AdmissionError(f"target process XML parse failed: {exc}") from exc
    uuid=text_of(root.find("./p:processInformation/p:dataSetInformation/common:UUID",NS)); version=text_of(root.find("./p:administrativeInformation/p:publicationAndOwnership/common:dataSetVersion",NS)); location=root.find("./p:processInformation/p:geography/p:locationOfOperationSupplyOrProduction",NS); reference_year=text_of(root.find("./p:processInformation/p:time/common:referenceYear",NS)); valid_until=text_of(root.find("./p:processInformation/p:time/common:dataSetValidUntil",NS)); registration=text_of(root.find("./p:administrativeInformation/p:publicationAndOwnership/common:registrationNumber",NS)); license_type=text_of(root.find("./p:administrativeInformation/p:publicationAndOwnership/common:licenseType",NS)); access=text_of(root.find("./p:administrativeInformation/p:publicationAndOwnership/common:accessRestrictions",NS)); owner_node=root.find("./p:administrativeInformation/p:publicationAndOwnership/common:referenceToOwnershipOfDataSet/common:shortDescription",NS); auth_node=root.find("./p:administrativeInformation/p:publicationAndOwnership/common:referenceToRegistrationAuthority/common:shortDescription",NS); review=root.find("./p:modellingAndValidation/p:validation/p:review",NS); review_org=root.find("./p:modellingAndValidation/p:validation/p:review/common:referenceToNameOfReviewerAndInstitution/common:shortDescription",NS)
    require(uuid==EXPECTED["uuid"],"dataset UUID mismatch"); require(version==EXPECTED["version"],"dataset version mismatch"); require(english_basename(root)==EXPECTED["name"],"dataset English name mismatch"); require(location is not None and location.attrib.get("location")==EXPECTED["location"],"dataset location mismatch"); require(reference_year==EXPECTED["reference_year"],"reference year mismatch"); require(valid_until==EXPECTED["valid_until"],"valid-until mismatch"); require(registration==EXPECTED["registration_number"],"registration number mismatch"); require(text_of(owner_node)==EXPECTED["owner"],"dataset owner mismatch"); require(text_of(auth_node)==EXPECTED["registration_authority"],"registration authority mismatch"); require(root.attrib.get(f"{{{NS['epd2']}}}epd-version")==EXPECTED["format_version"],"ILCD+EPD version mismatch"); require(review is not None and review.attrib.get("type")=="Accredited third party review","published review metadata mismatch"); require(text_of(review_org)==EXPECTED["registration_authority"],"published reviewer identity mismatch"); require(license_type=="Free of charge for all users and uses","dataset license text mismatch"); require(access=="None","dataset access restriction mismatch")
    ref_id=text_of(root.find("./p:processInformation/p:quantitativeReference/p:referenceToReferenceFlow",NS)); require(ref_id is not None,"referenceToReferenceFlow missing"); ref_exchange=None
    for exchange in root.findall("./p:exchanges/p:exchange",NS):
        if exchange.attrib.get("dataSetInternalID")==ref_id: ref_exchange=exchange; break
    require(ref_exchange is not None,"reference exchange missing"); ref_flow=ref_exchange.find("./p:referenceToFlowDataSet",NS); require(ref_flow is not None,"reference flow dataset missing"); ref_flow_uuid=ref_flow.attrib.get("refObjectId"); ref_flow_name=text_of(ref_flow.find("./common:shortDescription",NS)); ref_amount=text_of(ref_exchange.find("./p:meanAmount",NS)); require(ref_amount=="1","reference exchange amount mismatch")
    gwp=None
    for result in root.findall("./p:LCIAResults/p:LCIAResult",NS):
        method=result.find("./p:referenceToLCIAMethodDataSet",NS)
        if method is None or method.attrib.get("refObjectId")!=EXPECTED["gwp_indicator_uuid"]: continue
        matches=[a for a in result.findall("./common:other/epd:amount",NS) if a.attrib.get(f"{{{NS['epd']}}}module")==EXPECTED["gwp_module"]]; require(len(matches)==1,"expected exactly one GWP-total A1-A3 amount"); value=text_of(matches[0]); require(value is not None,"GWP-total A1-A3 value missing"); canonical_decimal(value,"GWP-total A1-A3"); require(value==EXPECTED["gwp_value_decimal"],"GWP-total A1-A3 value mismatch"); unit_ref=result.find("./common:other/epd:referenceToUnitGroupDataSet",NS); unit_label=text_of(unit_ref.find("./common:shortDescription",NS)) if unit_ref is not None else None; gwp={"indicator_uuid":EXPECTED["gwp_indicator_uuid"],"indicator":"GWP-total","module":EXPECTED["gwp_module"],"scenario":None,"value_decimal":value,"source_unit_label":unit_label}; break
    require(gwp is not None,"GWP-total result missing")
    return {"uuid":uuid,"version":version,"name":EXPECTED["name"],"location":EXPECTED["location"],"reference_year":int(reference_year),"valid_until":int(valid_until),"registration_number":registration,"owner":text_of(owner_node),"registration_authority":text_of(auth_node),"format":"ILCD+EPD v1.2","published_review":{"type":review.attrib.get("type"),"reviewer":text_of(review_org),"source_metadata_only":True},"published_rights":{"license_type":license_type,"access_restrictions":access},"declared_reference":{"reference_exchange_internal_id":ref_id,"reference_flow_uuid":ref_flow_uuid,"reference_flow_short_description":ref_flow_name,"quantity_decimal":ref_amount,"declared_unit_from_process_description":"m3","source_internal_name_differs_from_process_title":"C 30/37" in (ref_flow_name or "") and "C25/30" not in (ref_flow_name or "")},"indicator_control":gwp}
def verify_package_manifest(obj):
    require(obj.get("dataset_uuid")==EXPECTED["uuid"],"canonical package UUID mismatch"); require(obj.get("requested_version")==EXPECTED["version"],"canonical package version mismatch"); require(obj.get("member_count")==EXPECTED["package_member_count"],"canonical package member count mismatch"); require(obj.get("package_content_manifest_sha256")==EXPECTED["package_content_manifest_sha256"],"canonical package content digest mismatch"); require(obj.get("target_process_path")==EXPECTED["process_path"],"canonical target process path mismatch"); require(obj.get("target_process_sha256")==EXPECTED["process_sha256"],"canonical target process digest mismatch"); require(obj.get("target_process_size_bytes")==EXPECTED["process_size"],"canonical target process size mismatch"); members=obj.get("members"); require(isinstance(members,list) and len(members)==EXPECTED["package_member_count"],"canonical package members malformed"); paths=[m.get("path") for m in members]; require(paths==sorted(paths) and len(set(paths))==len(paths),"canonical package paths must be unique and sorted"); target=[m for m in members if m.get("path")==EXPECTED["process_path"]]; require(len(target)==1 and target[0].get("sha256")==EXPECTED["process_sha256"],"target process member binding mismatch")
def verify_manifest(source):
    require(source.get("manifest_version")=="3.1.0","source manifest version mismatch"); require(source.get("source_role")=="PUBLIC_REAL_ENVIRONMENTAL_DECLARATION_CONTROL","source role mismatch"); dataset=source.get("dataset",{}); require(dataset.get("uuid")==EXPECTED["uuid"] and dataset.get("version")==EXPECTED["version"],"source manifest dataset identity mismatch"); frozen=source.get("frozen_source",{}); require(frozen.get("state")=="FROZEN","source manifest is not frozen"); require(frozen.get("package_content_manifest_sha256")==EXPECTED["package_content_manifest_sha256"],"source manifest package digest mismatch"); require(frozen.get("package_member_count")==EXPECTED["package_member_count"],"source manifest member count mismatch"); require(frozen.get("target_process_path")==EXPECTED["process_path"],"source manifest process path mismatch"); require(frozen.get("target_process_sha256")==EXPECTED["process_sha256"],"source manifest process digest mismatch"); require(frozen.get("terms_page_sha256")==EXPECTED["terms_sha256"],"source manifest terms digest mismatch"); require(frozen.get("extended_view_sha256")==EXPECTED["extended_sha256"],"source manifest extended-view digest mismatch"); require(frozen.get("zip_wrapper_sha256_authoritative") is False,"volatile ZIP wrapper cannot be authority"); rights=source.get("rights",{}); require(rights.get("read_use")=="ALLOWED","read/use authority missing"); require(rights.get("storage_for_analysis")=="ALLOWED","storage authority missing"); require(rights.get("transformation_for_analysis")=="ALLOWED","transformation authority missing"); require(rights.get("unmodified_redistribution")=="ALLOWED_WITH_SOURCE_ATTRIBUTION","unmodified redistribution authority mismatch"); require(rights.get("modified_or_raw_redistribution")=="UNKNOWN_REQUIRES_SEPARATE_EVIDENCE","modified/raw redistribution must remain unknown"); require(rights.get("scientific_validity_guaranteed_by_provider") is False,"scientific guarantee overclaim"); require(rights.get("professional_suitability_inferred") is False,"professional suitability overclaim"); require(rights.get("certification_authority_inferred") is False,"certification authority overclaim")
def verify_external_bytes(terms,extended):
    require(len(terms)==EXPECTED["terms_size"] and sha(terms)==EXPECTED["terms_sha256"],"terms page identity mismatch"); require(len(extended)==EXPECTED["extended_size"] and sha(extended)==EXPECTED["extended_sha256"],"extended service view identity mismatch"); lower=terms.lower()
    for marker in (b"free of charge",b"without any restrictions",b"free distribution of unmodified data",b"source is named",b"no responsibility for the accuracy"): require(marker in lower,f"published terms marker missing: {marker!r}")
    require(EXPECTED["uuid"].encode() in extended,"extended service view UUID mismatch"); require(EXPECTED["version"].encode() in extended,"extended service view version mismatch")
def verify_profile(profile):
    require(profile.get("profile_name")=="EPD 1.2 ÖKOBAUDAT","wrong official profile name"); require(profile.get("profile_version")=="3.8.0","wrong official profile version"); require(profile.get("error_count")==0,"official ÖKOBAUDAT profile reported errors"); require(profile.get("is_positive") is True,"official ÖKOBAUDAT profile did not mark package positive"); return {"profile_name":profile.get("profile_name"),"profile_version":profile.get("profile_version"),"error_count":profile.get("error_count"),"warning_count":profile.get("warning_count"),"event_count":profile.get("event_count"),"positive":profile.get("is_positive")}
def build_record(source,package,process_bytes,terms,extended,profile):
    verify_manifest(source); verify_package_manifest(package); verify_external_bytes(terms,extended); process=parse_process(process_bytes); profile_summary=verify_profile(profile); discrepancy=bool(process["declared_reference"]["source_internal_name_differs_from_process_title"])
    record={"schema_version":"1.0","record_type":"ProofGridRealEnvironmentalSourceAdmission","verdict":VERDICT,"source":{"provider":"ÖKOBAUDAT","dataset_uuid":EXPECTED["uuid"],"dataset_version":EXPECTED["version"],"package_content_manifest_sha256":EXPECTED["package_content_manifest_sha256"],"package_member_count":EXPECTED["package_member_count"],"target_process_path":EXPECTED["process_path"],"target_process_sha256":EXPECTED["process_sha256"],"terms_sha256":EXPECTED["terms_sha256"],"extended_view_sha256":EXPECTED["extended_sha256"],"zip_wrapper_sha256_is_authority":False},"dataset_identity":process,"rights":{"read_use":"ALLOWED","storage_for_analysis":"ALLOWED","transformation_for_analysis":"ALLOWED","commercial_analysis_use":"ALLOWED_BY_PUBLISHED_UNRESTRICTED_USE_TERMS","unmodified_redistribution":"ALLOWED_WITH_SOURCE_ATTRIBUTION","modified_or_raw_redistribution":"UNKNOWN_REQUIRES_SEPARATE_EVIDENCE","source_attribution_required_for_unmodified_redistribution":True},"conformance":{"format":"ILCD+EPD v1.2","official_oekobaudat_profile":profile_summary,"profile_validation_performed":True,"profile_compatible":True},"admission":{"admitted_for_normalization":True,"mapping_eligible":False,"mapping_block_reason":"EXPLICIT_SUITABILITY_REVIEW_REQUIRED","source_internal_naming_discrepancy_present":discrepancy,"impact_calculation_allowed_by_this_record":False},"authority_boundaries":{"scientific_validity_proven_by_admission":False,"professional_suitability_proven_by_admission":False,"regulator_acceptance_implied":False,"certified":False,"building_result_reviewed":False,"ifc_mapping_performed":False,"building_impact_calculation_performed":False},"limitations":["Admission establishes exact-source rights, identity, and format/profile conformance only.","The source reference-flow short description is preserved verbatim; its naming differs from the process title and requires explicit suitability review before mapping.","Published dataset third-party review metadata is source metadata and is not independent review of any future ProofGrid building result.","No IFC mapping, building impact calculation, whole-building completeness, regulator acceptance, or certification follows from this record."],"integrity":{"content_sha256":ZERO,"canonicalization":CANON,"signature":None}}
    record["integrity"]["content_sha256"]=sha(cbytes(record)); validate_record(record); return record
def validate_record(record):
    require(record.get("verdict")==VERDICT,"wrong v3.1 verdict"); require(record.get("admission",{}).get("admitted_for_normalization") is True,"normalization admission missing"); require(record.get("admission",{}).get("mapping_eligible") is False,"mapping promotion rejected"); require(record.get("admission",{}).get("impact_calculation_allowed_by_this_record") is False,"calculation promotion rejected"); require(record.get("conformance",{}).get("profile_validation_performed") is True,"profile validation missing"); require(record.get("conformance",{}).get("profile_compatible") is True,"profile compatibility missing"); boundaries=record.get("authority_boundaries",{})
    for key in ("scientific_validity_proven_by_admission","professional_suitability_proven_by_admission","regulator_acceptance_implied","certified","building_result_reviewed","ifc_mapping_performed","building_impact_calculation_performed"): require(boundaries.get(key) is False,f"authority promotion rejected: {key}")
    require(record.get("rights",{}).get("modified_or_raw_redistribution")=="UNKNOWN_REQUIRES_SEPARATE_EVIDENCE","modified/raw redistribution overclaim")
def make_receipt(record,raw):
    receipt={"verdict":VERDICT,"engine":{"name":ENGINE_NAME,"version":ENGINE_VERSION},"record_content_sha256":record["integrity"]["content_sha256"],"record_file_sha256":sha(raw),"dataset_uuid":EXPECTED["uuid"],"dataset_version":EXPECTED["version"],"package_content_manifest_sha256":EXPECTED["package_content_manifest_sha256"],"target_process_sha256":EXPECTED["process_sha256"],"terms_sha256":EXPECTED["terms_sha256"],"extended_view_sha256":EXPECTED["extended_sha256"],"profile_validation_performed":True,"profile_compatible":True,"admitted_for_normalization":True,"mapping_eligible":False,"certified":False}; receipt["receipt_sha256"]=sha(cbytes(receipt)); return receipt
def main(argv=None):
    p=argparse.ArgumentParser(); p.add_argument("--source-manifest",type=Path,required=True); p.add_argument("--package-manifest",type=Path,required=True); p.add_argument("--process-xml",type=Path,required=True); p.add_argument("--terms-page",type=Path,required=True); p.add_argument("--extended-view",type=Path,required=True); p.add_argument("--profile-result",type=Path,required=True); p.add_argument("--output-dir",type=Path,required=True); a=p.parse_args(argv)
    try:
        source,_=load_json(a.source_manifest); package,_=load_json(a.package_manifest); profile,_=load_json(a.profile_result); record=build_record(source,package,a.process_xml.read_bytes(),a.terms_page.read_bytes(),a.extended_view.read_bytes(),profile); a.output_dir.mkdir(parents=True,exist_ok=True); raw=pbytes(record); (a.output_dir/"real-environmental-source-admission.json").write_bytes(raw); receipt=make_receipt(record,raw); (a.output_dir/"real-environmental-source-admission-receipt.json").write_bytes(pbytes(receipt))
    except Exception as exc: print(f"FAILED: {exc}",file=sys.stderr); return 2
    print(f"RESULT: {VERDICT}"); print("ADMITTED_FOR_NORMALIZATION=true"); print("MAPPING_ELIGIBLE=false"); print("CERTIFIED=false"); return 0
if __name__=="__main__": raise SystemExit(main())
